simpleblog/config/routes.rb
Rails.application.routes.draw do
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html

  root 'posts#index'

  get 'about' => 'pages#about'

  resources :posts
end

simpleblog/app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

simpleblog/app/models/post.rb
class Post < ApplicationRecord

	validates :title, presence: true,
	lenth: {minimum: 5}
end

simpleblog/app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

simpleblog/app/controllers/pages_controller.rb
class PagesController < ApplicationController

	def about
		@title ="About us"
			 @content = "This is an about page"
	end
	
end

simpleblog/app/controllers/posts_controller.rb
class PostsController < ApplicationController
	 def index
	 	@posts= Post.all
	 	
	 end 

	 def show
	 	@post= Post.find(params[:id])
	 	end
	 def new 
	 	@post = Post.new
	 end
	 def create 
		#render plain: params[:post].inspect
		@post = Post.new(post_params)
		#@post.save
		if(@post.save)
			redirect_to @post
		else 
			render 'new'
		end
			end


	private def post_params
		params.require(:post).permit(:title, :body)
	end
end 

simpleblog/app/helpers/application_helper.rb
module ApplicationHelper
end

simpleblog/app/helpers/pages_helper.rb
module PagesHelper
end

simpleblog/app/helpers/posts_helper.rb
module PostsHelper
end

simpleblog/app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Simpleblog</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_pack_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <%= yield %>
  </body>
</html>

simpleblog/app/views/pages/about.html.erb
<h1><%= @title %></h1>
<p><%= @content %></p>

simpleblog/app/views/posts/index.html.erb
<h1>Blog Posts</h1>


<% @posts.each do |post| %>

	<h1> <%= @post.title %></h1>
	<p> <%= @post.body %></p>
	<%= link_to 'New post', post_path %>
	 
<% end %>

simpleblog/app/views/posts/new.html.erb
<h1>Add posts</h1>

<%= form_for :post, url: posts_path do |f| %>

<% if @post.errors.any? %>
    <div id="error_explanation">
      <h2>
        <%= pluralize(@post.errors.count, "error") %> title is too short
      </h2>
      <ul>
        <% @post.errors.full_messages.each do |msg| %>
          <li><%= msg %></li>
        <% end %>
      </ul>
    </div>
  <% end %>
<p> 
	<%= f.label :title %><br>
	<%= f.text_field :title %></p>

	<p> <%= f.label :body %><br>
	<%= f.text_area :body %></p>

	<p> 
		<%= f.submit %>
	</p>
	<% end %>

simpleblog/app/views/posts/show.html.erb
<h1> <%= @post.title %></h1>
<p> <%= @post.body %></p>
<%= link_to 'Back', posts_path %>