LoginApp/config/routes.rb
Rails.application.routes.draw do
  get 'static_pages/home'
  get 'static_pages/help'
  get 'static_pages/about'
  get 'static_pages/contact'
	root 'static_pages#home'
	 get '/home', to: 'static_pages#home'
	 get '/help', to: 'static_pages#help'
get '/about',to: 'static_pages#about'
get '/contact', to: 'static_pages#contact'

  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
 
 
  get 'sessions/new'
    get '/logout', to: 'sessions#destroy'
get '/signup', to: 'users#new'
get '/login', to: 'sessions#new'
post '/login', to: 'sessions#create'
delete '/logout', to: 'sessions#destroy'
resources :users

end

LoginApp/app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

LoginApp/app/models/user.rb
class User < ApplicationRecord
attr_accessor :remember_token
before_save { self.email = email.downcase }
validates :name, presence: true, length: { maximum: 50 }

VALID_EMAIL_REGEX = /\A[\w+\-.]+@[a-z\d\-.]+\.[a-z]+\z/i
validates :email, presence: true, length: { maximum: 255 },
format: { with: VALID_EMAIL_REGEX },
uniqueness: { case_sensitive: false }

validates :phone,  :numericality => true, :length => { :minimum => 10, :maximum => 10 }



has_secure_password
validates :password, presence: true, length: { minimum: 6 }
# Returns the hash digest of the given string.
def User.digest(string)
cost = ActiveModel::SecurePassword.min_cost ? BCrypt::Engine::MIN_COST
:
BCrypt::Engine.cost
BCrypt::Password.create(string, cost: cost)
end
# Returns a random token.
def User.new_token
SecureRandom.urlsafe_base64
end
# Remembers a user in the database for use in persistent sessions.
def remember
self.remember_token = User.new_token
update_attribute(:remember_digest, User.digest(remember_token))
end
# Returns true if the given token matches the digest.
def authenticated?(remember_token)
	return false if remember_digest.nil?
BCrypt::Password.new(remember_digest).is_password?(remember_token)
end

def forget
update_attribute(:remember_digest, nil)
end



end

LoginApp/app/controllers/account_activations_controller.rb
class AccountActivationsController < ApplicationController
end

LoginApp/app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
protect_from_forgery with: :exception
include SessionsHelper
private
# Confirms a logged-in user.
def logged_in_user
unless logged_in?
store_location
flash[:danger] = "Please log in."
redirect_to login_url
end
end
end

LoginApp/app/controllers/sessions_controller.rb
class SessionsController < ApplicationController
def new
end

def create
user = User.find_by(email: params[:session][:email].downcase)
if user && user.authenticate(params[:session][:password])
log_in user

redirect_to user
else
flash.now[:danger] = 'Invalid email/password combination'
render 'new'
end
end
def destroy
log_out if logged_in?
redirect_to root_url
end
end

LoginApp/app/controllers/static_pages_controller.rb
class StaticPagesController < ApplicationController
  def home

end

  def help
  end

  def about
  end

  def contact
  end
end

LoginApp/app/controllers/users_controller.rb
class UsersController < ApplicationController

#signup
def show
	@user = User.find(params[:id])
end
def new
@user = User.new
end

def create
@user = User.new(user_params)
if @user.save
log_in @user
flash[:success] = "Welcome to the Sample App!"
redirect_to @user
else
render 'new'
end
end
private
def user_params
params.require(:user).permit(:name, :email, :password, :password_confirmation, :gender, :DOB, :address, :phone)
end
end
#signup

LoginApp/app/helpers/account_activations_helper.rb
module AccountActivationsHelper
end

LoginApp/app/helpers/application_helper.rb
module ApplicationHelper
end

LoginApp/app/helpers/sessions_helper.rb
module SessionsHelper
	# Logs in the given user.
def log_in(user)
session[:user_id] = user.id
end

def remember(user)
user.remember
cookies.permanent.signed[:user_id] = user.id
cookies.permanent[:remember_token] = user.remember_token
end
# Returns the user corresponding to the remember token cookie.
def current_user
if (user_id = session[:user_id])
@current_user ||= User.find_by(id: user_id)
elsif (user_id = cookies.signed[:user_id])
user = User.find_by(id: user_id)
if user && user.authenticated?(cookies[:remember_token])
log_in user
@current_user = user
end
end
end
# Returns true if the user is logged in, false otherwise.
def logged_in?
!current_user.nil?end
end

def log_out
session.delete(:user_id)
@current_user = nil
end

# Forgets a persistent session.
def forget(user)
user.forget
cookies.delete(:user_id)
cookies.delete(:remember_token)
end
# Logs out the current user.
def log_out
forget(current_user)
session.delete(:user_id)
@current_user = nil

end

LoginApp/app/helpers/static_pages_helper.rb
module StaticPagesHelper
end

LoginApp/app/helpers/users_helper.rb
module UsersHelper
# Returns the Gravatar for the given user.
def gravatar_for(user, size: 80)
gravatar_id = Digest::MD5::hexdigest(user.email.downcase)
gravatar_url = "https://secure.gravatar.com/
avatar/#{gravatar_id}?s=#{size}"
image_tag(gravatar_url, alt: user.name, class: "gravatar")
end
end

LoginApp/app/views/layouts/_header.html.erb
<header >

<%= link_to "LoginApp", root_path, id: "logo" %>

<ul >
<li><%= link_to "Home", root_path %></li>
<li><%= link_to "Help", help_path %></li>
<li><%= link_to "Contact", contact_path %></li>
<% if logged_in? %>
<a href="#" Account <b ></b></a>

<li><%= link_to "Profile", current_user %></li>
<li>
<%= link_to "Log out", logout_path, method: "delete" %>
</li>

</li>
<% else %>
<li><%= link_to "Log in", login_path %></li>
<% end %>
</ul>

</header>

LoginApp/app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>LoginApp</title>

  </head>

  <body>
<%= render 'layouts/header' %>

	<% flash.each do |message_type, message| %>
<%= content_tag(:div, message, class: "alert
alert-#{message_type}") %>
<% end %>
<%= yield %>

<%= debug(params) if Rails.env.development? %>

</body>
</html>

LoginApp/app/views/shared/_error_messages.html.erb
<% if @user.errors.any? %>

The form contains <%= pluralize(@user.errors.count, "error") %>.

<ul>
<% @user.errors.full_messages.each do |msg| %>
<li><%= msg %></li>
<% end %>
</ul>

<% end %>

LoginApp/app/views/static_pages/about.html.erb
<% provide(:title, "About") %>
<!DOCTYPE html>
<html>
<head>
<title><%= yield(:title) %> | Ruby on Rails Tutorial Sample
App</title>
</head>
<body>
<h1>About</h1>
<p>
The <a href="http://www.railstutorial.org/"><em>Ruby on Rails
Tutorial</em></a> is a
<a href="http://www.railstutorial.org/book">book</a> and
<a href="http://screencasts.railstutorial.org/">screencast
series</a>
to teach web development with
<a href="http://rubyonrails.org/">Ruby on Rails</a>.
This is the sample application for the tutorial.
</p>
</body>
</html>

LoginApp/app/views/static_pages/contact.html.erb
<% provide(:title, 'Contact') %>
<h1>Contact</h1><p>
Contact the Ruby on Rails Tutorial about the sample app at the
<a href="http://www.railstutorial.org/contact">contact page</a>.
</p>

LoginApp/app/views/static_pages/help.html.erb
<h1>Help</h1>
<p>
Get help on the Ruby on Rails Tutorial at the
<a href="http://www.railstutorial.org/help">Rails Tutorial help
page</a>.
To get help on this sample app, see the
<a href="http://www.railstutorial.org/book"><em>Ruby on Rails
Tutorial</em>
book</a>.
</p>

LoginApp/app/views/static_pages/home.html.erb
<h1>Welcome to the Hospital</h1>
<h2>
This is the home page for the
<a href="http://www.railstutorial.org/">Ruby on Rails Tutorial</a>
sample application.
</h2>
<%= link_to "Sign up now!", signup_path%>

LoginApp/app/views/users/new.html.erb
<% provide(:title, 'Sign up') %>
<h1>Sign up</h1>

<%= form_for(@user) do |f| %>
<%= render 'shared/error_messages' %><br><br>
<%= f.label :name %>
<%= f.text_field :name %><br><br>

<%= f.label :gender %>
      <%= f.radio_button :gender, 'male', :checked => true %> 
  <%= label :gender_Male, 'Male' %>
  <%= f.radio_button :gender, 'female' %>
  <%= label :gender_Female, 'Female' %><br><br>

<%= f.label :DOB, "Date Of Birth " %>
<%= f.date_field :DOB %><br><br>
<%= f.label :email %>
<%= f.email_field :email %><br><br>
<%= f.label :address %>
<%= f.text_area :address %><br><br>
<%= f.label :phone %>
<%= f.telephone_field :phone %><br><br>
<%= f.label :password %>
<%= f.password_field :password %><br><br>
<%= f.label :password_confirmation, "Confirmation" %>
<%= f.password_field :password_confirmation %>
<%= f.submit "Create my account" %>

<% end %>

LoginApp/app/views/users/show.html.erb
<!-- SignUp--><% provide(:title, @user.name) %>

<h1>
<%= gravatar_for @user %>
<%= @user.name %>
</h1>

<!-- SignUp-->